name: Daily API Update

on:
  schedule:
    - cron: '*/5 * * * *'  # 12:01 AM EST
  workflow_dispatch:

jobs:
  post-to-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call Generate Daily API
        run: |
          curl -X POST "https://uwguessr.com/api/generate-daily"
